
const ERR_INTERNAL = 1
const ERR_INVALID_PARAMETERS = 2
const ERR_INVALID_SYNTAX = 3
const ERR_KID_ALREADY_EXISTS = 4
const ERR_INCORRECT_KEK = 5

const JSON_CONTENT_TYPE = 'application/json'

module.exports = {
  ERR_INTERNAL,
  ERR_INVALID_PARAMETERS,
  ERR_INVALID_SYNTAX,
  ERR_INCORRECT_KEK,
  ERR_KID_ALREADY_EXISTS,
  JSON_CONTENT_TYPE
}
